package com.example.sparks.Controllers;

import com.example.sparks.Repositories.StateRepository;

import org.json.JSONObject;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
// import org.springframework.web.bind.annotation.RequestMapping;
// import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/district") // This means URL's start with /demo (after Application path)
@CrossOrigin
public class DistrictController {
    // @Autowired // This means to get the bean called userRepository
    //      // Which is auto-generated by Spring, we will use it to handle the data
    // private StateRepository stateRepository;
}
